### ISSUE TITLE
Difficulty generating dot files

### ISSUE THREAD

**Issue by ds2643** [bmeg/protograph#16]
On the current `bmeg/master` branch, I'm encountering some difficulty generating `dot` files from `protograph.yaml` files.

There are three `protograph.yaml` files currently checked into the repository:
```
λ ~/protograph/ master* find . -type f -name "*yaml"                                       
./resources/config/protograph.yaml
./resources/test/bmeg.protograph.yaml
./src/test/bmeg.protograph.yaml
```

Of these three files, the latter two produce empty dot files:
```
λ ~/protograph/ master* lein run -m protograph.dot -p ./src/test/bmeg.protograph.yaml
λ ~/protograph/ master* cat protograph.dot 
digraph protograph {
}%                                                                                                      
λ ~/protograph/ master* lein run -m protograph.dot -p ./resources/test/bmeg.protograph.yaml
λ ~/protograph/ master* cat protograph.dot 
digraph protograph {
}%                           
```

The first file `./resources/config/protograph.yaml`, yields a stacktrace:
```
λ ~/protograph/ master* lein run -m protograph.dot -p ./resources/config/protograph.yaml
Exception in thread "main" java.lang.ClassCastException: clojure.lang.PersistentArrayMap cannot be cast 
to java.util.Map$Entry, compiling:(/tmp/form-init7297760142193589453.clj:1:73)                         
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.ClassCastException: clojure.lang.PersistentArrayMap cannot be cast to java.util.Map
$Entry                                                                                                 
        at clojure.lang.APersistentMap$KeySeq.first(APersistentMap.java:166)
        at clojure.lang.RT.first(RT.java:667)
        at clojure.lang.SeqIterator.next(SeqIterator.java:49)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__6744.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__6744.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6545)
        at clojure.core$mapv.invokeStatic(core.clj:6618)
        at clojure.core$mapv.invoke(core.clj:6618)
        at protograph.dot$emit_dot.invokeStatic(dot.clj:21)
        at protograph.dot$emit_dot.invoke(dot.clj:16)
        at protograph.dot$_main.invokeStatic(dot.clj:38)
        at protograph.dot$_main.doInvoke(dot.clj:34)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at user$eval5.invokeStatic(form-init7297760142193589453.clj:1)
        at user$eval5.invoke(form-init7297760142193589453.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        ... 14 more
```
This stacktrace seems to indicate that `protograph/emit-dot` has trouble processing its input.

I suspect that the computation of the local variable `edges` in the `emit-dot`'s definition causes the issue:
```
(defn emit-dot
  [protograph]
  (let [graph (template/graph-structure protograph)
        nodes (keys (:vertexes graph))
        edges (reduce set/union #{} (vals (:from graph)))
        out-nodes (mapv emit-node nodes)
        out-edges (mapv emit-edge edges)
        header "digraph protograph {"
        footer "}"
        all (reduce into [[header] out-nodes out-edges [footer]])]
    (string/join "\n" all)))
```

@prismofeverything: Is this behavior expected? To my knowledge my repository is in a state mirroring the upstream master branch. Additionally, I believe I encountered similar issues when reverting to the previous commit on `master`. Please let me know if you can reproduce the issue, or if my input is incorrect.

**Comment by prismofeverything** [comment]
Hi David,

It is helpful to witness your outside perspective as you work to understand the repo, thanks for your effort.

In this case the three protograph files in the repository are misleading and out of date. Our canonical protograph file is in a different repo: https://github.com/biostream/bmeg-etl/blob/master/bmeg.protograph.yaml

That said, there was an error in `protograph.dot` I have fixed as well, so it should be working now.

I will clean up the other example protograph files around so they do not mislead others. Thanks again!

**Comment by ds2643** [comment]
@prismofeverything, thanks for getting back to me. You may have mentioned files stored in the other repository in our first exchange, so I apologize if I made you repeat yourself.

Should we consider consolidating these test files into `resources`?

**Comment by ds2643** [comment]
Also, we can probably close this issue now that you've addressed my question.

**Comment by ds2643** [comment]
On a related note, would you be interested in doing some kind of validation on the `yaml` inputs? Perhaps a schema description with `spec` might be a helpful feature.

**Comment by prismofeverything** [comment]
Ah yes, I have been meaning to do some kind of validation for awhile now. Have you used spec before? Would definitely be interested in this.

**Comment by ds2643** [comment]
@prismofeverything, I've used both `spec` and `schema` before. I'd recommend `spec`, which I've had a good experience using. Let's continue discussion on issue #11.
